name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Backend Checks
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Frontend Checks
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Docker Build Test (Sabse Zaroori)
      - name: Docker Compose Build Check
        run: docker-compose build